### ISSUE TITLE
运行后直接闪退 

### ISSUE THREAD

**Issue by LeeTech** [aa112901/remusic#11]
09-25 15:53:19.072 1617-1617/com.wm.remusic I/libpersona: KNOX_SDCARD checking this for 10538
09-25 15:53:19.072 1617-1617/com.wm.remusic I/libpersona: KNOX_SDCARD not a persona
09-25 15:53:19.072 1617-1617/com.wm.remusic E/Zygote: v2
09-25 15:53:19.072 1617-1617/com.wm.remusic I/SELinux: Function: selinux_compare_spd_ram, index[1], SPD-policy is existed. and_ver=SEPF_SM-N9100_5.1.1 ver=51
09-25 15:53:19.072 1617-1617/com.wm.remusic W/SELinux: Function: selinux_compare_spd_ram, index[1], priority [2], priority version is VE=SEPF_SECMOBILE_6.0.1_0013
09-25 15:53:19.082 1617-1617/com.wm.remusic E/Zygote: accessInfo : 0
09-25 15:53:19.082 1617-1617/com.wm.remusic W/SELinux: SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.wm.remusic 
09-25 15:53:19.082 1617-1617/com.wm.remusic I/art: Late-enabling -Xcheck:jni
09-25 15:53:19.122 1617-1617/com.wm.remusic D/TimaKeyStoreProvider: TimaSignature is unavailable
09-25 15:53:19.122 1617-1617/com.wm.remusic D/ActivityThread: Added TimaKeyStore provider
09-25 15:53:20.252 1617-1617/com.wm.remusic D/SecWifiDisplayUtil: Metadata value : none
09-25 15:53:20.252 1617-1617/com.wm.remusic D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{ea86aa4 V.E...... R.....I. 0,0-0,0}
09-25 15:53:20.252 1617-1711/com.wm.remusic D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-25 15:53:20.322 1617-1617/com.wm.remusic W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-25 15:53:20.352 31245-31245/com.wm.remusic:main D/MusicPlaybackService: Creating service
09-25 15:53:20.352 31245-31245/com.wm.remusic:main D/MediaPlayerProxy: port 45506 obtained
09-25 15:53:20.352 31245-1729/com.wm.remusic:main D/MediaPlayerProxy: running
09-25 15:53:20.362 1617-1617/com.wm.remusic E/showorhide: 0
09-25 15:53:20.372 31245-31245/com.wm.remusic:main V/MediaPlayer-JNI: native_setup
09-25 15:53:20.372 31245-31245/com.wm.remusic:main E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
09-25 15:53:20.372 31245-31245/com.wm.remusic:main E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
09-25 15:53:20.372 31245-31245/com.wm.remusic:main V/MediaPlayer: constructor
09-25 15:53:20.372 31245-31245/com.wm.remusic:main V/MediaPlayer: setListener
09-25 15:53:20.372 31245-31245/com.wm.remusic:main V/MusicPlaybackService: Scheduling shutdown in 300000 ms
09-25 15:53:20.372 31245-31245/com.wm.remusic:main W/System.err: java.io.FileNotFoundException: /data/user/0/com.wm.remusic/cacheplaylist: open failed: ENOENT (No such file or directory)
09-25 15:53:20.372 31245-31245/com.wm.remusic:main W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
09-25 15:53:20.372 31245-31245/com.wm.remusic:main W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
09-25 15:53:20.372 31245-31245/com.wm.remusic:main W/System.err:     at com.wm.remusic.service.MediaService.reloadQueue(MediaService.java:1575)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at com.wm.remusic.service.MediaService.reloadQueueAfterPermissionCheck(MediaService.java:1547)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at com.wm.remusic.service.MediaService.onCreate(MediaService.java:385)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3807)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at android.app.ActivityThread.access$2100(ActivityThread.java:221)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at android.os.Looper.loop(Looper.java:158)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7225)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at libcore.io.Posix.open(Native Method)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)
09-25 15:53:20.382 31245-31245/com.wm.remusic:main W/System.err: 	... 13 more
09-25 15:53:20.382 31245-31245/com.wm.remusic:main D/MusicPlaybackService: notifyChange: what = com.wm.remusic.queuechanged
09-25 15:53:20.382 31245-31245/com.wm.remusic:main D/MusicPlaybackService: notifyChange: what = com.wm.remusic.metachanged
09-25 15:53:20.402 31245-31245/com.wm.remusic:main D/MusicPlaybackService: Got new intent Intent { cmp=com.wm.remusic/.service.MediaService }, startId = 1
09-25 15:53:20.402 31245-31245/com.wm.remusic:main D/MusicPlaybackService: handleCommandIntent: action = null, command = null
09-25 15:53:20.402 31245-31245/com.wm.remusic:main V/MusicPlaybackService: Scheduling shutdown in 300000 ms
09-25 15:53:20.402 31245-31245/com.wm.remusic:main D/MusicPlaybackService: Service bound, intent = Intent { cmp=com.wm.remusic/.service.MediaService }
09-25 15:53:20.402 31245-31245/com.wm.remusic:main D/MusicPlaybackService: Cancelling delayed shutdown, scheduled = true
09-25 15:53:20.482 1617-1617/com.wm.remusic I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
09-25 15:53:20.592 1617-1617/com.wm.remusic D/AbsListView: Get MotionRecognitionManager
09-25 15:53:20.592 1617-1617/com.wm.remusic E/MotionRecognitionManager: mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@ee21d79
09-25 15:53:20.592 1617-1617/com.wm.remusic E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@fd79abe
09-25 15:53:20.592 1617-1617/com.wm.remusic E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@fd79abe
09-25 15:53:20.742 1617-1617/com.wm.remusic D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{b501e I.ED..... R.....ID 0,0-0,0}
09-25 15:53:20.752 1617-1711/com.wm.remusic I/Adreno: QUALCOMM build                   : 570dfa1, Ibb8f3faafb
                                                      Build Date                       : 04/21/16
                                                      OpenGL ES Shader Compiler Version: XE031.06.00.05
                                                      Local Branch                     : 
                                                      Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.BF.2.1.2_RB1.06.00.01.182.007
                                                      Remote Branch                    : NONE
                                                      Reconstruct Branch               : NOTHING
09-25 15:53:20.762 1617-1711/com.wm.remusic D/libEGL: eglInitialize EGLDisplay = 0x9fbc07c4
09-25 15:53:20.762 1617-1711/com.wm.remusic I/OpenGLRenderer: Initialized EGL, version 1.4
09-25 15:53:20.862 1617-1738/com.wm.remusic E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                              Process: com.wm.remusic, PID: 1617
                                                              java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                  at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                  at java.lang.Thread.run(Thread.java:818)
                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.wm.remusic.adapter.MainFragmentAdapter.updateResults(java.util.ArrayList, java.util.ArrayList, java.util.ArrayList)' on a null object reference
                                                                  at com.wm.remusic.fragment.MainFragment$2.doInBackground(MainFragment.java:161)
                                                                  at com.wm.remusic.fragment.MainFragment$2.doInBackground(MainFragment.java:146)
                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                  at java.lang.Thread.run(Thread.java:818) 
09-25 15:53:21.352 1617-1778/com.wm.remusic E/action-cache: http://tingapi.ting.baidu.com/v1/restserver/ting?from=android&version=5.6.5.6&format=json&method=baidu.ting.plaza.getFocusPic&num=7
09-25 15:53:21.462 1617-1617/com.wm.remusic D/AbsListView: viewType is heaer or footer
09-25 15:53:21.482 31245-32465/com.wm.remusic:main D/MusicPlaybackService: notifyChange: what = com.wm.remusic.metachanged
09-25 15:53:21.502 1617-1794/com.wm.remusic E/ActivityThread: Failed to find provider info for null
09-25 15:53:21.502 1617-1794/com.wm.remusic E/ActivityThread: Failed to find provider info for null
09-25 15:53:21.532 1617-1778/com.wm.remusic E/cache: {"pic":[{"randpic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14746894292356070b94767c20832aba6da1f81b73.jpg","randpic_ios5":"","randpic_desc":"\u4f60\u5728\u7ec8\u70b9\u7b49\u6211","randpic_ipad":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474689437a9c48bbf4c958ba4a430fd8571eacb1a.jpg","randpic_qq":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14746894397fc951a579a280eb1bb71e93deb912aa.jpg","randpic_2":"bos_client_14746894333efd80d3762ab8f25d6daaac99c3939f","randpic_iphone6":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14746894333efd80d3762ab8f25d6daaac99c3939f.jpg","special_type":0,"ipad_desc":"\u4f60\u5728\u7ec8\u70b9\u7b49\u6211","is_publish":"111111","mo_type":"2","type":2,"code":"271832019"},{"randpic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14746000401acd3a81d0a45ddf8a6c8952d1eba54a.jpg","randpic_ios5":"","randpic_desc":"\u65b0\u6b4c\u699c","randpic_ipad":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474600057f88d54907da17d5375869af55cbedcf9.jpg","randpic_qq":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14746000669e33229d7e6932ddbcb8a243caa1b8b6.jpg","randpic_2":"bos_client_1474600052ec13411d55b552cb53323d1568a0d846","randpic_iphone6":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474600052ec13411d55b552cb53323d1568a0d846.jpg","special_type":0,"ipad_desc":"\u65b0\u6b4c\u699c","is_publish":"111111","mo_type":"5","type":7,"code":"354530048"},{"randpic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14746096752cbc337c3e9da876bc26301cd1fbf207.jpg","randpic_ios5":"","randpic_desc":"T\u699c\u8bbf\u8c08\u5708","randpic_ipad":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474609684094e46f7ddd284fdd242f5f6588f5f0c.jpg","randpic_qq":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474609695ba3bf9f1798546437a4d10f35d072f61.jpg","randpic_2":"bos_client_147460967949c8cc12e8b28688d1b744eeb5242ef0","randpic_iphone6":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_147460967949c8cc12e8b28688d1b744eeb5242ef0.jpg","special_type":0,"ipad_desc":"T\u699c\u8bbf\u8c08\u5708","is_publish":"111111","mo_type":"4","type":6,"code":"http:\/\/music.baidu.com\/cms\/webview\/TbangInterview24\/index.html"},{"randpic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474690777de064d7b37a6b7b3d7aa42d8eec56819.jpg","randpic_ios5":"","randpic_desc":"\u4e70\u767e\u5ea6\u97f3\u4e50VIP\u9001\u7231\u5947\u827a\u4f53\u9a8c\u4f1a\u5458","randpic_ipad":"","randpic_qq":"","randpic_2":"bos_client_1474690783ed981c821a2c49d2ee07738e2af50edd","randpic_iphone6":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474690783ed981c821a2c49d2ee07738e2af50edd.jpg","special_type":0,"ipad_desc":"\u4e70\u767e\u5ea6\u97f3\u4e50VIP\u9001\u7231\u5947\u827a\u4f53\u9a8c\u4f1a\u5458","is_publish":"111111","mo_type":"4","type":6,"code":"http:\/\/music.baidu.com\/cms\/webview\/vip_activity\/aiqiyi_vip"},{"randpic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474534775fc7a97d9d849746a5bac25c1112cbd82.jpg","randpic_ios5":"","randpic_desc":"\u7ea2","randpic_ipad":"","randpic_qq":"","randpic_2":"bos_client_147453478570a32706ecd3796229b64397a2dd58b4","randpic_iphone6":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_147453478570a32706ecd3796229b64397a2dd58b4.jpg","special_type":0,"ipad_desc":"\u7ea2","is_publish":"111111","mo_type":"4","type":6,"code":"http:\/\/music.baidu.com\/cms\/webview\/topic_activity\/baokuan_01\/?from=android_music_homeBanner"},{"randpic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14745290732ca0e3732e4a025a7a9957632793833f.jpg","randpic_ios5":"","randpic_desc":"\u66b4\u98ce","randpic_ipad":"","randpic_qq":"","randpic_2":"bos_client_14745290774c185d831a4d12334d7bc873585d975a","randpic_iphone6":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14745290774c185d831a4d12334d7bc873585d975a.jpg","special_type":0,"ipad_desc":"\u66b4\u98ce","i
09-25 15:53:21.542 1617-1617/com.wm.remusic D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
09-25 15:53:21.542 1617-1617/com.wm.remusic I/Choreographer: Skipped 45 frames!  The application may be doing too much work on its main thread.
09-25 15:53:21.542 1617-1711/com.wm.remusic D/libGLESv1: DTS_GLAPI : DTS is not allowed for Package : com.wm.remusic
09-25 15:53:21.652 1617-1809/com.wm.remusic E/action-cache: http://tingapi.ting.baidu.com/v1/restserver/ting?from=android&version=5.8.1.0&channel=ppzs&operator=3&method=baidu.ting.plaza.index&cuid=89CF1E1A06826F9AB95A34DC0F6AAA14
09-25 15:53:21.712 1617-1809/com.wm.remusic E/cache: {"result":{"mix_1":{"error_code":22000,"result":[{"desc":"王菲","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14746895224367a6de6f7dc000c50962ca55c964a2.jpg","type_id":"271832019","type":2,"title":"你在终点等我","tip_type":0,"author":"王菲"},{"desc":"何洁","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474610699eacdd2f6dc31ad3baf947fd9122fce19.jpg","type_id":"271789305","type":2,"title":"不服来犟","tip_type":0,"author":"何洁"},{"desc":"SNH48","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474601341debc4be1e3e0feef411210ed3f572624.jpg","type_id":"271770536","type":2,"title":"公主披风","tip_type":0,"author":"SNH48"},{"desc":"ZERO-G","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_147460130882e611d26135c71be467f853e7f0492e.jpg","type_id":"269196918","type":2,"title":"一击即中","tip_type":0,"author":"ZERO-G"},{"desc":"吴斌\/马海生\/俞思远\/王啸坤","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474512815f42a394306048a9d71b0fec5c94fc1f5.jpg","type_id":"271733407","type":2,"title":"不遇见","tip_type":0,"author":"吴斌\/马海生\/俞思远\/王啸坤"},{"desc":"王心凌\/佟梦实","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474423294184254f98fa27396ea386c4fed51a6e9.jpg","type_id":"271696828","type":2,"title":"冤家路窄","tip_type":0,"author":"王心凌\/佟梦实"},{"desc":"刘维\/袁成杰","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_147442322099172c6d698702854348e273026b846a.jpg","type_id":"271695572","type":2,"title":"大包子","tip_type":3,"author":"刘维\/袁成杰"},{"desc":"尚雯婕","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14744190617cfd61389eb7abb4b6fd0b4914d935b0.jpg","type_id":"271687014","type":2,"title":"Extremology 极端者","tip_type":0,"author":"尚雯婕"},{"desc":"The Invisible","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474336353de91f92cfa340e314fc6094351ed8e78.jpg","type_id":"271628313","type":2,"title":"Life's Dancers","tip_type":0,"author":"The Invisible"},{"desc":"方大同","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14743005933365d916197fd7592c35bc0a037c9818.jpg","type_id":"271663956","type":2,"title":"很不低调","tip_type":0,"author":"方大同"},{"desc":"孙燕姿","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474175323c27da14104adff4204f1b5b7210da3c1.jpg","type_id":"271553878","type":2,"title":"彩虹金刚","tip_type":0,"author":"孙燕姿"},{"desc":"薛凯琪","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474257193c47a7a456f8d9e71cfc794413c92e2a2.jpg","type_id":"271652022","type":2,"title":"十年后的我","tip_type":0,"author":"薛凯琪"},{"desc":"许志安","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_147425698160346111fe960482785b1ca84c74a63e.jpg","type_id":"271651709","type":2,"title":"非安全地带","tip_type":0,"author":"许志安"},{"desc":"崔子格","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_14742531675ac00c0babb355bfbc714231ca4f06d6.jpg","type_id":"271628936","type":2,"title":"小喇叭","tip_type":0,"author":"崔子格"},{"desc":"薛仕凌\/王诗安","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_147425298581294df62d2016b92a2c56a990abd515.jpg","type_id":"271633034","type":2,"title":"HOME Remix","tip_type":0,"author":"薛仕凌\/王诗安"},{"desc":"孙子涵","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474252953433a8490a05935b75801422b5afdb9bf.jpg","type_id":"271632079","type":2,"title":"回忆那么伤","tip_type":0,"author":"孙子涵"},{"desc":"简迷离","pic":"http:\/\/business.cdn.qianqian.com\/qianqian\/pic\/bos_client_1474180823ded515d37dbb6b3f46ee0ba60fae32da.jpg","type_id":"271490971","type":2,"title":"简 GEneration","tip_type":0,"author":"简迷离"},{"desc":"韩红","pic":"http:\/\/business.cdn.qianqian.com
09-25 15:53:21.782 1617-1617/com.wm.remusic D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
09-25 15:53:21.812 1617-1617/com.wm.remusic D/AbsListView: viewType is heaer or footer
09-25 15:53:21.912 31245-31245/com.wm.remusic:main D/MusicPlaybackService: Service unbound
09-25 15:53:21.912 31245-31245/com.wm.remusic:main D/MusicPlaybackService: Destroying service
09-25 15:53:21.912 31245-31245/com.wm.remusic:main V/MediaPlayer-JNI: get_session_id()
09-25 15:53:21.912 1617-1617/com.wm.remusic D/ViewRootImpl: #3 mView = null
09-25 15:53:21.922 31245-31245/com.wm.remusic:main V/MediaPlayer-JNI: release
09-25 15:53:21.922 31245-31245/com.wm.remusic:main V/MediaPlayer: setListener
09-25 15:53:21.922 31245-31245/com.wm.remusic:main V/MediaPlayer: disconnect
09-25 15:53:21.922 31245-31245/com.wm.remusic:main V/MediaPlayer: destructor
09-25 15:53:21.922 31245-31245/com.wm.remusic:main V/MediaPlayer: disconnect
09-25 15:53:21.922 1617-1617/com.wm.remusic E/WindowManager: android.view.WindowLeaked: Activity com.wm.remusic.activity.MainActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{ea86aa4 V.E...... R....... 0,0-1440,2560} that was originally added here
                                                                 at android.view.ViewRootImpl.<init>(ViewRootImpl.java:569)
                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:326)
                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
                                                                 at android.app.Dialog.show(Dialog.java:350)
                                                                 at com.wm.remusic.widget.SplashScreen$1.run(SplashScreen.java:84)
                                                                 at android.app.Activity.runOnUiThread(Activity.java:6035)
                                                                 at com.wm.remusic.widget.SplashScreen.show(SplashScreen.java:95)
                                                                 at com.wm.remusic.activity.MainActivity.onCreate(MainActivity.java:45)
                                                                 at android.app.Activity.performCreate(Activity.java:6876)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
09-25 15:53:21.922 1617-1617/com.wm.remusic D/ViewRootImpl: #3 mView = null
09-25 15:53:22.602 1617-1617/com.wm.remusic D/AndroidRuntime: Shutting down VM
09-25 15:53:22.602 1617-1617/com.wm.remusic I/Process: Sending signal. PID: 1617 SIG: 9
09-25 15:53:26.912 31245-31253/com.wm.remusic:main V/MediaPlayer-JNI: native_finalize
09-25 15:53:26.912 31245-31253/com.wm.remusic:main V/MediaPlayer-JNI: release

**Comment by excellentGit** [comment]
6.0以上需要在代码中加上文件读取权限。源主还没加判断代码。自己加下就可以了。
