### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wjdaima** [aa112901/remusic#119]
as可以运行，但是没有数据。报错显示
java.lang.NullPointerException: uriString
W/System.err:     at android.net.Uri$StringUri.<init>(Uri.java:479)
W/System.err:     at android.net.Uri$StringUri.<init>(Uri.java)
W/System.err:     at android.net.Uri.parse(Uri.java:441)
W/System.err:     at com.wm.remusic.fragment.QuickControlsFragment.updateNowplayingCard(QuickControlsFragment.java:188)
W/System.err:     at com.wm.remusic.fragment.QuickControlsFragment.updateTrackInfo(QuickControlsFragment.java:251)
W/System.err:     at com.wm.remusic.activity.BaseActivity.updateTrackInfo(BaseActivity.java:54)
W/System.err:     at com.wm.remusic.activity.BaseActivity$PlaybackStatus.onReceive(BaseActivity.java:237)

**Comment by kissjerryfan** [comment]
请问解决了吗
